version: '3.8'

services:
  signer:
    build: signer
    init: true
    volumes:
    - ./conf/zones:/zones:ro

  ns:
    build: https://github.com/johanix/tdns.git#ac635fbc679430260bae3ba02ac7c96b291d9a70
    init: true
    depends_on:
    - resolver
    ports:
    - "1053:53/tcp"
    - "1053:53/udp"
    networks:
      middle:
        ipv4_address: 10.16.1.3
    volumes:
    - ./ns/conf:/etc/axfr.net:ro
    - ./ns/resolv.conf:/etc/resolv.conf
    - tdns:/storage
    restart: unless-stopped

  resolver:
    image: cznic/knot-resolver:v5.7.1
    init: true
    command: ["-c", "/etc/knot-resolver/kresd.conf", "-n"]
    ports:
    - "53/tcp"
    - "53/udp"
    networks:
      middle:
        ipv4_address: 10.16.1.2
    volumes:
    - ./resolver/conf/kresd.conf:/etc/knot-resolver/kresd.conf:ro

volumes:
  tdns:

networks:
  # Note that it is required that the front network ranks lower (in lexical order by
  # name) than the other networks. See https://github.com/docker/docker/issues/27101
  middle:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 10.16.1.0/24
        gateway: 10.16.1.1
