version: '3.8'

services:
  ns:
    build: https://github.com/johanix/tdns.git#ac635fbc679430260bae3ba02ac7c96b291d9a70
    init: true
    ports:
    - "1053:53/tcp"
    - "1053:53/udp"
    volumes:
    - ./conf:/etc/axfr.net
    - tdns:/storage
    restart: unless-stopped

volumes:
  tdns:
