version: '3.8'

# NSCONFDIR must be set in the .env file
# For "parent"
#   NSCONFDIR=conf
# For "schild"
#   NSCONFDIR=schildconf
# For "uchild"
#   NSCONFDIR=uchildconf
services:
  ns:
    build: ns
    init: true
    networks:
      middle:
        ipv4_address: 10.16.1.4
    ports:
    - "${EXTDNSPORT:-53}:53/tcp"
    - "${EXTDNSPORT:-53}:53/udp"
    volumes:
    - ./ns/${NSCONFDIR}:/etc/bind

  tdns:
    build: https://github.com/johanix/tdns.git#776b2b67229cd7fb4deb2dc58fe19e1eb5666ba5
    init: true
    depends_on:
    - ns
    - resolver
    networks:
      middle:
        ipv4_address: 10.16.1.3
    volumes:
    - ./tdns/conf:/etc/axfr.net:ro
    - tdns:/storage
    restart: unless-stopped

  resolver:
    image: cznic/knot-resolver:v5.7.1
    init: true
    command: ["-c", "/etc/knot-resolver/kresd.conf", "-n"]
    networks:
      middle:
        ipv4_address: 10.16.1.2
    volumes:
    - ./resolver/conf/kresd.conf:/etc/knot-resolver/kresd.conf:ro

volumes:
  tdns:

networks:
  # Note that it is required that the front network ranks lower (in lexical order by
  # name) than the other networks. See https://github.com/docker/docker/issues/27101
  middle:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 10.16.1.0/24
        gateway: 10.16.1.1
